apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge  
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    isSyncedFromSupervisor: "yes"
  name: veritas-storage-policy
parameters:
  svStorageClass: veritas-storage-policy
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
